[supervisord]
nodaemon=true
loglevel=debug
logfile=/dev/null
pidfile=/tmp/supervisord.pid
socketfile=/tmp/supervisor.sock
chmod=0700

[unix_http_server]
file=/tmp/supervisor.sock
chmod=0700

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:horizon]
command=php /var/www/html/artisan horizon
directory=/var/www/html
autostart=true
autorestart=false
stdout_logfile=/proc/1/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/proc/1/fd/2
stderr_logfile_maxbytes=0
user=www-data

[program:redis-stream-consumer]
command=php /var/www/html/artisan redis:stream-consume --worker=1
directory=/var/www/html
autostart=true
autorestart=false
stdout_logfile=/proc/1/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/proc/1/fd/2
stderr_logfile_maxbytes=0
user=www-data

[program:laravel-scheduler]
command=php /var/www/html/artisan schedule:work
directory=/var/www/html
autostart=true
autorestart=false
stdout_logfile=/proc/1/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/proc/1/fd/2
stderr_logfile_maxbytes=0
user=www-data