#!/usr/bin/env bash
# =============================================================================
# SCR Platform — frontend container entrypoint
# =============================================================================
# Responsibilities:
#   1. Configure Next.js dev server to work with nginx reverse proxy
#   2. Wire up .env.local (copied from .env.sample if the repo has one)
#   3. npm install (idempotent)
#   4. Hand off to `npm run dev`
# =============================================================================

set -e

APP_DIR=/app
cd "$APP_DIR"

log() { echo "[entrypoint] $*"; }

# -----------------------------------------------------------------------------
# 1. Sanity check — scr-frontend is expected to be cloned from GitHub into
#    FRONTEND_PATH with its package.json already committed. We no longer
#    scaffold a fresh Next.js app here.
# -----------------------------------------------------------------------------
if [ ! -f "$APP_DIR/package.json" ]; then
    log "ERROR: no package.json found in $APP_DIR."
    log "Make sure FRONTEND_PATH points at a checked-out scr-frontend repo."
    exec "$@"
fi

# -----------------------------------------------------------------------------
# 2. Update next.config.ts for container networking + local.scr.com routing
# -----------------------------------------------------------------------------
NEXT_CONFIG="$APP_DIR/next.config.ts"
if [ -f "$NEXT_CONFIG" ] && ! grep -q "SCR_LOCAL_DOCKER_PATCH" "$NEXT_CONFIG"; then
    log "Patching next.config.ts for local.scr.com dev server access..."
    cat > "$NEXT_CONFIG" <<'EOF'
// SCR_LOCAL_DOCKER_PATCH — managed by local-docker/node/entrypoint.sh.
// Re-running the stack will not overwrite this file once this marker exists,
// so feel free to customize further after the first boot.
import type { NextConfig } from 'next'

const nextConfig: NextConfig = {
  /* config options here */
  // Allow requests from local.scr.com domain through nginx proxy
  experimental: {
    // Enable experimental features if needed
  },
}

export default nextConfig
EOF
fi

# -----------------------------------------------------------------------------
# 3. Wire up .env.local — copy .env.sample (committed in the repo) if
#    present, otherwise fall back to the inline defaults below.
# -----------------------------------------------------------------------------
ENV_LOCAL="$APP_DIR/.env.local"
ENV_SAMPLE="$APP_DIR/.env.sample"
if [ ! -f "$ENV_LOCAL" ]; then
    if [ -f "$ENV_SAMPLE" ]; then
        log "No .env.local found — copying .env.sample..."
        cp "$ENV_SAMPLE" "$ENV_LOCAL"
    else
        log "No .env.local or .env.sample found — creating .env.local with defaults..."
        cat > "$ENV_LOCAL" <<EOF
# Auto-generated by local-docker entrypoint
NEXT_PUBLIC_API_BASE_URL=http://${APP_DOMAIN:-local.scr.com}/api
EOF
    fi
fi

# -----------------------------------------------------------------------------
# 4. Dependencies (named volume persists node_modules/ across restarts)
# -----------------------------------------------------------------------------
# Checking "node_modules/ exists and is non-empty" is NOT a reliable signal
# that install finished — an npm install interrupted partway through (e.g.
# `docker compose down` mid-run, or the container getting restarted before
# it completes) leaves a non-empty-but-incomplete node_modules behind, and
# `npm run dev` then fails with "next: not found" on every subsequent boot
# because this check never re-triggers. Instead, verify the actual binary
# Next.js needs exists; re-run npm install (idempotent) whenever it doesn't.
if [ ! -x "$APP_DIR/node_modules/.bin/next" ]; then
    log "next binary missing (no or incomplete node_modules/) — running npm install..."
    npm install
fi

# -----------------------------------------------------------------------------
# 5. Hand off to the real process
# -----------------------------------------------------------------------------
log "Starting: $*"
exec "$@"
