#!/usr/bin/env bash
# =============================================================================
# SCR Platform — frontend container entrypoint
# =============================================================================
# Responsibilities:
#   1. Bootstrap a fresh Next.js 16 + TypeScript app into /app if it's
#      empty (only when AUTO_BOOTSTRAP=true)
#   2. Configure Next.js dev server to work with nginx reverse proxy
#   3. npm install (idempotent)
#   4. Hand off to `npm run dev`
# =============================================================================

set -e

APP_DIR=/app
cd "$APP_DIR"

log() { echo "[entrypoint] $*"; }

# -----------------------------------------------------------------------------
# 1. Bootstrap fresh Next.js app if missing
# -----------------------------------------------------------------------------
if [ "${AUTO_BOOTSTRAP:-true}" = "true" ] && [ ! -f "$APP_DIR/package.json" ]; then
    log "No frontend app found in $APP_DIR — bootstrapping Next.js 16 + TypeScript..."
    # Remove any partial scaffold left behind by a prior interrupted run
    # (container restart mid-bootstrap) — otherwise `npx create-next-app` fails
    # with "target directory is not empty" on every subsequent boot.
    rm -rf "$APP_DIR/tmp-install"
    npx create-next-app@latest tmp-install --typescript --tailwind --eslint --app --src-dir --import-alias "@/*" --no-git --yes
    # Using `cp -a` + `rm -rf` rather than `mv`: $APP_DIR/node_modules already
    # exists as a Docker named-volume mount point (declared in
    # docker-compose.yml) by the time this runs. `mv` would try to rename any
    # same-named source directory directly on top of that mount point, which
    # fails — `cp -a` copies file-by-file instead, which works fine (mirrors
    # the fix applied to the backend entrypoint for the same underlying
    # reason with storage/ and vendor/).
    shopt -s dotglob
    cp -a tmp-install/. "$APP_DIR"/
    rm -rf tmp-install
    shopt -u dotglob
    log "Next.js scaffold created."

    # Packages aligned with project needs: Tanstack Query,  Socket.io
    log "Installing Tanstack Query,  Socket.io client..."
    npm install \
        @tanstack/react-query \
        socket.io-client
fi

if [ ! -f "$APP_DIR/package.json" ]; then
    log "ERROR: no package.json found and AUTO_BOOTSTRAP is disabled."
    log "Either set AUTO_BOOTSTRAP=true or create the Next.js app manually at ${FRONTEND_PATH}."
    exec "$@"
fi

# -----------------------------------------------------------------------------
# 2. Update next.config.ts for container networking + local.scr.com routing
# -----------------------------------------------------------------------------
NEXT_CONFIG="$APP_DIR/next.config.ts"
if [ -f "$NEXT_CONFIG" ] && ! grep -q "SCR_LOCAL_DOCKER_PATCH" "$NEXT_CONFIG"; then
    log "Patching next.config.ts for local.scr.com dev server access..."
    cat > "$NEXT_CONFIG" <<'EOF'
// SCR_LOCAL_DOCKER_PATCH — managed by local-docker/node/entrypoint.sh.
// Re-running the stack will not overwrite this file once this marker exists,
// so feel free to customize further after the first boot.
import type { NextConfig } from 'next'

const nextConfig: NextConfig = {
  /* config options here */
  // Allow requests from local.scr.com domain through nginx proxy
  experimental: {
    // Enable experimental features if needed
  },
}

export default nextConfig
EOF
fi

# -----------------------------------------------------------------------------
# 3. Create .env.local with environment variables for Next.js
# -----------------------------------------------------------------------------
ENV_LOCAL="$APP_DIR/.env.local"
if [ ! -f "$ENV_LOCAL" ]; then
    log "Creating .env.local with environment variables..."
    cat > "$ENV_LOCAL" <<EOF
# Auto-generated by local-docker entrypoint
NEXT_PUBLIC_API_BASE_URL=http://${APP_DOMAIN:-local.scr.com}/api
EOF
fi

# -----------------------------------------------------------------------------
# 4. Dependencies (named volume persists node_modules/ across restarts)
# -----------------------------------------------------------------------------
# Checking "node_modules/ exists and is non-empty" is NOT a reliable signal
# that install finished — an npm install interrupted partway through (e.g.
# `docker compose down` mid-run, or the container getting restarted before
# it completes) leaves a non-empty-but-incomplete node_modules behind, and
# `npm run dev` then fails with "next: not found" on every subsequent boot
# because this check never re-triggers. Instead, verify the actual binary
# Next.js needs exists; re-run npm install (idempotent) whenever it doesn't.
if [ ! -x "$APP_DIR/node_modules/.bin/next" ]; then
    log "next binary missing (no or incomplete node_modules/) — running npm install..."
    npm install
fi

# -----------------------------------------------------------------------------
# 5. Hand off to the real process
# -----------------------------------------------------------------------------
log "Starting: $*"
exec "$@"
